# Generated by Django 5.2.3 on 2025-06-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='seats',
            new_name='seat',
        ),
        migrations.AddField(
            model_name='bus',
            name='no_of_seats',
            field=models.PositiveBigIntegerField(default=30),
            preserve_default=False,
        ),
    ]
