# Generated by Django 5.2.3 on 2025-06-29 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_seats_seat_bus_no_of_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat', to='bookings.bus'),
        ),
    ]
